name: Backend Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Check backend
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -c "import main"
        working-directory: ./backend